// <auto-generated />
using System;
using ComponentProcessing.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ComponentProcessing.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220819101344_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("ComponentProcessing.Models.ComponentProcessingModel", b =>
                {
                    b.Property<long>("requestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityColumn();

                    b.Property<string>("componentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("componentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("contactNumber")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("dateOfDelivery")
                        .HasColumnType("datetime2");

                    b.Property<long>("deliveryCharges")
                        .HasColumnType("bigint");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("packageCharges")
                        .HasColumnType("bigint");

                    b.Property<int>("quantity")
                        .HasColumnType("int");

                    b.Property<string>("status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("totalCharges")
                        .HasColumnType("bigint");

                    b.HasKey("requestId");

                    b.ToTable("componentProcessings");
                });
#pragma warning restore 612, 618
        }
    }
}
